"""Add LinkAccessLog table

Revision ID: 6a6703624952
Revises: 7a8d4b74bead
Create Date: 2025-12-14 16:49:43.897996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6703624952'
down_revision = '7a8d4b74bead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_access_log')
    # ### end Alembic commands ###
